### ISSUE TITLE
spm_superres input type issue.

### ISSUE THREAD

**Issue by chrisfoulon** [brudfors/spm_superres#1]
Hi Mikael,

I tried to run "spm_superres" but I had an error coming from the spm_superres_lib.m. 
alloc_vars calls create_nii, which calls file_array itself calling fname and fname tests if the parameter is a char array. But in spm_superres_lib.m line 93, the parameter fname_y is created by calling the fullfile function which returns a string. 
So in the end, fname receives a string and throws an error. 

https://github.com/brudfors/spm_superres/blob/704b9755609fca70651d5b67e3e183949ae828ed/spm_superres_lib.m#L93

I added a char() around the fname_y definition to cast it as a char array and it seems to go through after that. 

Hope it helps (tell me if I have done something wrong, I'm rather new with matlab and spm).

Have a great day, 

Chris Foulon.

**Comment by brudfors** [comment]
Hi Chris,

Thank you for reporting this issue. 

It seems as if a filename is a string object, fullfile(.) will return a string array, which errors in create_nii(.).

I just committed the fix fileparts(char(f)) to the code.

Best wishes,

Mikael
