### ISSUE TITLE
Edges between thick slices accentuated in upsampled image

### ISSUE THREAD

**Issue by johnaeanderson** [brudfors/spm_superres#2]
Hi Mikael,

First off, thanks so much for this software - this addresses our use case perfectly!  

The only thing I'm wondering about is whether you've run into the issue where upsampling accentuates the edges of the slices?  Some of these edges then get misinterpreted as grey matter in white matter for instance.

Any tips on dealing with this?

Thanks,

John

**Comment by brudfors** [comment]
Hi John,

I am glad you are finding it useful!

Are you using the MATLAB or the docker version? If you are using the MATLAB version then maybe you could try to change line 743 in spm_superres_lib.m to 0. This simulates a slice-gap, but could possibly be a non-optimal way of doing so. Setting it to zero assumes no gap between slices. If you do, please let me know if it helped.

Thank you for your input,

Mikael

**Comment by johnaeanderson** [comment]
Hi Mikael,

Thanks, I've tried modifying the Matlab script as you suggested and it doesn't seem to make a difference so far (I'm still getting the accentuation of the slices, see attached screenshots
![slice_gap](https://user-images.githubusercontent.com/3432462/84035159-59b64880-a969-11ea-8ac9-1cd913b3c9f3.png)
).

The reason I was using the Matlab version is I got this error whenever I tried to use the docker image.
`(base) john@Johns-MacBook-Pro ~ % docker run -ti --rm -v /Users/john/Documents/temp:/input mbrud/spm_superres


root@c0c0e53f48f3:/# /opt/spm12/spm12 function spm_superres input
SPM12, version 12.5 (standalone)
MATLAB, version 9.4.0.813654 (R2018a)
 ___  ____  __  __
/ __)(  _ \(  \/  )
\__ \ )___/ )    (   Statistical Parametric Mapping
(___/(__)  (_/\/\_)  SPM12 - https://www.fil.ion.ucl.ac.uk/spm/

c=3, i=1 | sd=4.254413, mu=233.240068 -> tau=0.055249, lam=0.042874
c=2, i=1 | sd=4.045925, mu=552.234034 -> tau=0.061089, lam=0.018108
c=1, i=1 | sd=4.786915, mu=464.072449 -> tau=0.043640, lam=0.021548
step-size -> rho=8.394103
Allocating niftis...done!

Running max 50 iterations:
Killed
root@c0c0e53f48f3:/#`

and it produces the following preallocations

Dyflair.nii
DyT1.nii
DyT2.nii
flair.nii
Hflair.nii
HT1.nii
HT2.nii
T1.nii
T2.nii
wflair.nii
wT1.nii
wT2.nii
yflair.nii
yT1.nii
yT2.nii
zflair.nii
zT1.nii
zT2.nii

**Comment by brudfors** [comment]
Hi John,

Okay, I see, that is actually an issue that I have faced before (when similar artefacts can be seen in the original thick-sliced image). I am working on a GPU implementation of the code and have changed the observation model a little bit. My plan was to integrate this modification into the MATLAB code, which hopefully will help reducing those dark streaks in the white matter. I will do it asap!

Regarding your Docker error message, it seems as if it could have to do with a memory error:

https://stackoverflow.com/questions/44417159/docker-process-killed-with-cryptic-killed-message

that is if you are using a mac. Increasing the memory limit should then help it seems.

Thank you,

Mikael

**Comment by johnaeanderson** [comment]
Hi Mikael,

Thanks for taking a look at this, I'm looking forward to trying the next version. 

You're right about the docker version being resource bound, it's running now with a greater allocation of memory - though much slower than within Matlab.  GPU acceleration definitely seems worthwhile in this case.

**Comment by brudfors** [comment]
Hi John,

Yes, it definitely isn't the fastest algorithm.. My current GPU version of the code runs a lot faster, so also allows for more optimal convergence, etc. Hopefully I can have a version ready fairly soon.

I will comment here when I have changed the observation model.

Thanks again for your input,

Mikael

**Comment by johnaeanderson** [comment]
Hi Mikael, any update on this? Thanks again!

**Comment by brudfors** [comment]
Hi John,

Sorry for the slow reply. I have not yet gotten around looking at this since I have been focusing on the Python GPU implementation for the last week. In this implementation I am exploring correcting your issue by introducing a slice-wise scaling factor. But I haven't gotten the implementation finished yet. By the way, just out of curiosity, would you be inclined to use a Python implementation, or are you more keen on MATLAB?

**Comment by johnaeanderson** [comment]
Hi Mikael, 
Thanks for the update, I'd be happy to use either Matlab or python.  The python implementation seems a bit smoother since you don't have to pre-specify which images to include it just grabs everything in the folder.  I think I could probably wrap that in a loop slightly more easily than I could with a Matlab implementation.

Best,

John

**Comment by brudfors** [comment]
Thanks! Will let you know when the python implementation is ready then, it is easier for me to focus on one implementation at a time :)

**Comment by brudfors** [comment]
Hi @johnaeanderson,

Realized I never got back to you regarding this issue. However, here is the Python implmementation of the code:

https://github.com/brudfors/UniRes

By default, it should correct for the artefact you are seeing:

https://github.com/brudfors/UniRes/blob/master/unires/struct.py#L102
