### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Arribarat** [brudfors/spm_superres#3]
Dear authors, 
Thank you for this work. This is exactly the type of program we are interested in. 
I tried to run it in MATLAB but I must be doing it wrong. 

Indeed, I get this error : 

SPM12: spm_coreg (v7320)                           17:25:08 - 22/02/2023
Completed                               :          17:25:19 - 22/02/2023
c=2, i=1 | sd=5.132125, mu=977.536484 -> tau=0.037967, lam=0.010230
c=1, i=1 | sd=18.645899, mu=768.228089 -> tau=0.002876, lam=0.013017
step-size -> rho=12.294546
Allocating niftis...done!

Running max 30 iterations:
Error using spm_superres>(parfor body) (line 283)
Matrix dimensions must agree.

Error in spm_superres (line 280)
        parfor (c=1:C,NumWorkers)

Do you know what this is due to? 
Thank you for your help, and congratulations again for this work. 
GA.

**Comment by brudfors** [comment]
Hello @Arribarat,

I am glad to hear that you are interested in trying our work!

What dimensions are your two input volumes?

**Comment by Arribarat** [comment]
Thanks for your reaction !

So, I started with a 2 volume MRI set: 
T1w MRI:  182 x 218 x 182 | 1mm x 1mm x 1mm. 
PDw MRI: 182 x 218 x 91 | 1mm x 1mm x 2mm. 
I got the error you saw before.

Then I used a 3 volume MRI set, asin your example : 
T1w MRI:  182 x 218 x 182 | 1mm x 1mm x 1mm. 
PDw MRI: 182 x 218 x 91 | 1mm x 1mm x 2mm.
T2w MRI:  182 x 218 x 91 | 1mm x 1mm x 2mm.
I get the same error. 

Then I used a 3 volume MRI set, isotropic resolution: 
T1w MRI:  121 x 145 x 121 | 1.5mm x 1.5mm x 1.5mm. 
PDw MRI: 121 x 145 x 121 | 1.5mm x 1.5mm x 1.5mm. 
T2w MRI:  121 x 145 x 121 | 1.5mm x 1.5mm x 1.5mm. 
I get the same error consistently. 

I guess I must be doing something wrong but I don't know what. I do have the latest version of SPM 12.
Thanks for your help,
GA.

**Comment by brudfors** [comment]
Thank you! 

Can you please share the output for the volumes in, e.g., your first run; from running this command:
```matlab
n = nifti('pth1.nii')
n.mat

n = nifti('pth2.nii')
n.mat
```
And also the output of this command:
```matlab
spm('version')
```

**Comment by Arribarat** [comment]
Below is the result of the command: 

>> n = nifti('ax_8860_t1w.nii') 
n =  
NIFTI object: 1-by-1
            dat: [182x218x182 file_array]
            mat: [4x4 double]
     mat_intent: 'Scanner'
           mat0: [4x4 double]
    mat0_intent: 'Scanner'
         timing: [1x1 struct]
        descrip: 'DEVIN.'

>>n.mat
ans =
    1.0000         0         0  -91.5000
         0    1.0000         0 -109.5000
         0         0    1.0000  -91.5000
         0         0         0    1.0000

>> n = nifti('ax_8860_dpw.nii')
 n =  
NIFTI object: 1-by-1
            dat: [182x218x91 file_array]
            mat: [4x4 double]
     mat_intent: 'Scanner'
           mat0: [4x4 double]
    mat0_intent: 'Scanner'
         timing: [1x1 struct]
        descrip: 'DEVIN.'
>> n.mat
ans =
    1.0000         0         0  -91.5000
         0    1.0000         0 -109.5000
         0         0    2.0000  -92.0000
         0         0         0    1.0000


>> spm('version')
ans =
SPM12 (7771)

**Comment by brudfors** [comment]
Unfortunately, I am not able to reproduce your error on the same SPM version. 

Could you try to replace:
```matlab
parfor (c=1:C,NumWorkers)
```
on line 280 with:
```matlab
for c=1:C
```
This will give a much more detailed error message.

**Comment by Arribarat** [comment]
Thank you for your feedback. 
I have made the change on line 280.
I now get the following error : 

SPM12: spm_coreg (v7320)                           14:35:06 - 23/02/2023
Completed                               :          14:35:17 - 23/02/2023
Starting parallel pool (parpool) using the 'local' profile ... connected to 6 workers.
c=2, i=1 | sd=4.693162, mu=967.255587 -> tau=0.045401, lam=0.010339
c=1, i=1 | sd=18.645899, mu=768.228089 -> tau=0.002876, lam=0.013017
step-size -> rho=13.304512
Allocating niftis...done!

Running max 30 iterations:
Error using  .* 

Matrix dimensions must agree.

Error in spm_superres (line 284)
            z  = mtv.*(Dy + w/rho);

**Comment by brudfors** [comment]
I think you might be running on a MATLAB version that does not support implicit expansion, can you try to replace line 284 with:
```matlab
z = bsxfun(@times, mtv, (Dy + w/rho));
```

**Comment by Arribarat** [comment]
It works!!! Thanks for your help! You are a genius! 
I ran the algorithm on my MRI T1 and PD set. As a reminder, the dimensions were :
T1w MRI: 182 x 218 x 182 | 1mm x 1mm x 1mm.
PDw MRI: 182 x 218 x 91 | 1mm x 1mm x 2mm.
I get 2 MRIs with the following dimensions: 
187 x 223 x 188 | 1mm x 1mm x 1mm.

![y_ax_8860_dpw](https://user-images.githubusercontent.com/23481937/220962085-f17e0d14-43db-45b3-a162-a0103b786251.png)
![y_ax_8860_t1w](https://user-images.githubusercontent.com/23481937/220962092-28a18f56-99f8-4991-8284-7673203c699c.png)
![ax_8860_t1w](https://user-images.githubusercontent.com/23481937/220962096-3d47f03e-57b1-4983-bee9-8c7398048570.png)

And... I have a big artifact on the reconstructed images. I'm uploading captures of the results, if you have any ideas... The "good image" T1 is the reference image. I saw earlier, in the dialog box, that a colleague had artefacts with the "slice gap". I tried to set it to 0, but the artefact is the same. It appears in the first few iterations.

Anyway, if you have an idea. In any case, thanks again for your help!
GA.

**Comment by brudfors** [comment]
Great the issue is solved, I will push a fix to the code!

I am not sure why you are seeing that issue, you could try increase the value of the regularisation:

https://github.com/brudfors/spm_superres/blob/master/spm_superres.m#L30

(e.g. try 100)

or increase the number of iterations:

https://github.com/brudfors/spm_superres/blob/master/spm_superres.m#L32

If you have access to a GPU you can also try the Python implemenation of this algorithm:

https://github.com/brudfors/UniRes

It is much faster and also optimises for decreasing the inter-leaved acquisition artefact you are seeing in the PD scan:
